spring:
  application:
    name: SpringBootDataCompare
  datasource:
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.6.129:3306/icbc?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
    secondary:
      url: jdbc:mysql://192.168.6.129:3306/summit?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
    third:
      url: jdbc:mysql://192.168.6.129:3306/summit_local?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
server:
  port: 8044
