spring:
  application:
    name: SpringBootDataCompare
  datasource1:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.6.129:3306/datasync?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource2:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.6.129:3306/datasource?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8044
